### ISSUE TITLE
Testing stuck

### ISSUE THREAD

**Issue by LHJ97** [DengPingFan/PraNet#10]
I followed the instructions stated in the readme to download all the wights and datasets, and put them in the corrected path. However when I started the test by running MyTest.py in command line, the code stuck when executing the line model = PraNet(). Could you please tell me where is the error or could you provide me with clearer tutorial to run your code?

Packages installed in the conda env:
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.10.14                    0  
certifi                   2020.11.8        py36h06a4308_0  
cffi                      1.14.4           py36h261ae71_0  
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
freetype                  2.10.4               h5ab3b9f_0  
intel-openmp              2020.2                      254  
jpeg                      9b                   h024ee3a_2  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
lz4-c                     1.9.2                heb0550a_3  
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py36hff7bd54_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openssl                   1.1.1h               h7b6447c_0  
pillow                    8.0.1            py36he98fc37_0  
pip                       20.3             py36h06a4308_0  
pycparser                 2.20                       py_2  
python                    3.6.12               hcff3b4d_2  
pytorch                   1.1.0           cuda100py36he554f03_0  
readline                  8.0                  h7b6447c_0  
scipy                     1.5.2            py36h0b6359f_0  
setuptools                50.3.2           py36h06a4308_2  
six                       1.15.0           py36h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
torchvision               0.3.0           cuda100py36h72fc40a_0  
wheel                     0.36.0             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0 

Thanks a lot!

**Comment by DengPingFan** [comment]
> I followed the instructions stated in the readme to download all the wights and datasets, and put them in the corrected path. However when I started the test by running MyTest.py in command line, the code stuck when executing the line model = PraNet(). Could you please tell me where is the error or could you provide me with clearer tutorial to run your code?
> 
> Packages installed in the conda env:
> _libgcc_mutex 0.1 main
> blas 1.0 mkl
> ca-certificates 2020.10.14 0
> certifi 2020.11.8 py36h06a4308_0
> cffi 1.14.4 py36h261ae71_0
> cudatoolkit 10.0.130 0
> cudnn 7.6.5 cuda10.0_0
> freetype 2.10.4 h5ab3b9f_0
> intel-openmp 2020.2 254
> jpeg 9b h024ee3a_2
> lcms2 2.11 h396b838_0
> ld_impl_linux-64 2.33.1 h53a641e_7
> libedit 3.1.20191231 h14c3975_1
> libffi 3.3 he6710b0_2
> libgcc-ng 9.1.0 hdf63c60_0
> libgfortran-ng 7.3.0 hdf63c60_0
> libpng 1.6.37 hbc83047_0
> libstdcxx-ng 9.1.0 hdf63c60_0
> libtiff 4.1.0 h2733197_1
> lz4-c 1.9.2 heb0550a_3
> mkl 2020.2 256
> mkl-service 2.3.0 py36he904b0f_0
> mkl_fft 1.2.0 py36h23d657b_0
> mkl_random 1.1.1 py36h0573a6f_0
> ncurses 6.2 he6710b0_1
> ninja 1.10.2 py36hff7bd54_0
> numpy 1.19.2 py36h54aff64_0
> numpy-base 1.19.2 py36hfa32c7d_0
> olefile 0.46 py36_0
> openssl 1.1.1h h7b6447c_0
> pillow 8.0.1 py36he98fc37_0
> pip 20.3 py36h06a4308_0
> pycparser 2.20 py_2
> python 3.6.12 hcff3b4d_2
> pytorch 1.1.0 cuda100py36he554f03_0
> readline 8.0 h7b6447c_0
> scipy 1.5.2 py36h0b6359f_0
> setuptools 50.3.2 py36h06a4308_2
> six 1.15.0 py36h06a4308_0
> sqlite 3.33.0 h62c20be_0
> tk 8.6.10 hbc83047_0
> torchvision 0.3.0 cuda100py36h72fc40a_0
> wheel 0.36.0 pyhd3eb1b0_0
> xz 5.2.5 h7b6447c_0
> zlib 1.2.11 h7b6447c_3
> zstd 1.4.5 h9ceee32_0
> 
> Thanks a lot!

I guess you may get out of the memory. Also, you may check your conda environment.

Best,

**Comment by LHJ97** [comment]
I listed the packages in my conda environment above. I am using Titan RTX 24Gb.
