### ISSUE TITLE
EvaluationTool

### ISSUE THREAD

**Issue by Kelly-Hero1** [DengPingFan/PraNet#11]
First of all thank you for your work. Then I have a question to ask you.
Are the data edges in your EvaluationTool extracted by code? I see that there is no groundtruth for the edges in the original datasets, so how do you measure the accuracy of the boundary by groundtruth ? Thank you！

**Comment by DengPingFan** [comment]
> First of all thank you for your work. Then I have a question to ask you.
> Are the data edges in your EvaluationTool extracted by code? I see that there is no groundtruth for the edges in the original datasets, so how do you measure the accuracy of the boundary by groundtruth ? Thank you！

Hi, Yes. the edges are derived from ground-truth by code. We do not specifically measure the accuracy of the boundary. We just simply conduct gradient operation for object-level ground-truth.
