### ISSUE TITLE
SFA

### ISSUE THREAD

**Issue by LYzb134143** [DengPingFan/PraNet#12]
Excuse me, where did you find the SFA code? Thank you

**Comment by DengPingFan** [comment]
https://github.com/Yuqi-cuhk/Polyp-Seg

**Comment by joe660** [comment]
> https://github.com/Yuqi-cuhk/Polyp-Seg

Hello, author, can you send me a copy? This connection won't open. My email address is 2362773974@qq.com

**Comment by DengPingFan** [comment]
Hi,

Very sorry. I have just found that the code has been removed by the
authors. You may need to Email the authors.


Best,

joe660 ***@***.***> 于2021年6月22日周二 下午5:58写道：

**Comment by Treamn** [comment]
Did you find SFA's code? if you find it, can u share with me?
