### ISSUE TITLE
Could you give more details about "res2net50_v1b_26w_4s"?

### ISSUE THREAD

**Issue by Cocofeat** [DengPingFan/PraNet#13]
Thanks for your code, it help me a lot.
It seems like you have pretrained the  res2net50 on your dataset? Can you provide more details? 
In other words, how do I train my data set?

**Comment by GewelsJI** [comment]
We only use the weights of res2net50, which is pretrained on ImageNet. More details refer to this git repo: https://github.com/Res2Net/Res2Net-PretrainedModels

**Comment by Cocofeat** [comment]
Thanks a lot

**Comment by Cocofeat** [comment]
Can I add your wechat so that we can contact real-time.? I try to send an email (gepengai.ji@163.com) to you, but there is wrong about your email address. My wechat name is Cocofeat.
