### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Bingo-Zuo** [DengPingFan/PraNet#17]
您好，请问您提供下载的数据集是CVC-ClinicDB数据集吗？测试集方便再提供一下吗，好像不能下载了。万分感谢！

**Comment by DengPingFan** [comment]
> 您好，请问您提供下载的数据集是CVC-ClinicDB数据集吗？测试集方便再提供一下吗，好像不能下载了。万分感谢！

你加我微信吧：ilovePing-G

**Comment by DengPingFan** [comment]
> 您好，请问您提供下载的数据集是CVC-ClinicDB数据集吗？测试集方便再提供一下吗，好像不能下载了。万分感谢！

你好，我刚才看了下载链接是没问题你的，google drive 你在国内可能需要翻墙
