### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by yukkyo** [DengPingFan/PraNet#18]
Thanks for the great research and code!
It is very helpful. 😆 

By the way, what is the license of this code?
Because I would like to use this code in other competitions.

**Comment by DengPingFan** [comment]
Hi, you can use it for research rather than for commercial.

Best,
Deng-Ping Fan
Research Scientist, IIAI, UAE.

y.fujimoto <notifications@github.com> 于2021年1月23日周六 下午10:12写道：

**Comment by yukkyo** [comment]
@DengPingFan 
Thanks!
