### ISSUE TITLE
How is the dice and iou calculated?

### ISSUE THREAD

**Issue by ydzhang12345** [DengPingFan/PraNet#19]
Hi,

Great project! Really appreciate. I got a question, since I am not familiar with Matlab, I am confused on the way you calculate dice and iou in eval.m. How do you choose the threshold value?

Thanks!

**Comment by DengPingFan** [comment]
Hi, 

We utilize 255 thresholds (0:1:255) to obtain 255 dice scores, then average these scores to obtain the final mean dice score.

**Comment by zihuanqiu** [comment]
Why use mean dice calculated in this method? I know mean dice may reflect some generalization ability, but few people will use a very low threshold as the margin for positive and negative class. I think 255 thresholds in uniform distributed may not quite proper? @DengPingFan 
Is the mean dice reported of other models used for comparison in your paper also based on this calculation method?
Thanks!

**Comment by DengPingFan** [comment]
Hi,

You can use other metrics to demonstrate the performance of the model.
Currently, we just show that under this metric, our model achieves the best
score. Using mean dice is similar like the mean F-measure, mean E-measure
metric used in many famous salient object detection (SOD) tasks. These
complete SOD models are summarized at: http://dpfan.net/socbenchmark.

Best,

Deng-Ping

zihuanqiu ***@***.***> 于2021年5月14日周五 下午1:11写道：
