### ISSUE TITLE
im getting this error :RuntimeError: Given input size: (320x1x1). Calculated output size: (320x0x0). Output size is too small

### ISSUE THREAD

**Issue by gunjan5489** [DengPingFan/PraNet#20]
Im using below repository to train on my dataset with normal and abnormal bubbles in a microscopic image 4000 x 4000.

please help or else some other repository to follow

https://github.com/james128333/HarDNet-MSEG

**Comment by DengPingFan** [comment]
Sorry, I don't quite understand your question.
