### ISSUE TITLE
Multi class attention module

### ISSUE THREAD

**Issue by BrennoCaldato** [DengPingFan/PraNet#21]
Hi, 
Thanks for making this code available.
Have you thought about how to expand the architecture to support more than one class? Would it be better to have one attention mask for each class? Or we can combine each label mask into one binary mask and use it for attention?

**Comment by DengPingFan** [comment]
Hi, 
Maybe you can refer our another project: https://github.com/DengPingFan/Inf-Net

Best,

Deng-Ping

**Comment by BrennoCaldato** [comment]
Thanks,

I quickly ran through the Inf-Net repository and noticed the Multi-Class model uses an Unet architecture without the reverse attention modules. May I ask why did you prefer to use Unet instead of extending the PraNet or the Inf-Net architecture to support multi-class segmentation?

Is there a way to build a multi-class PraNet architecture or there is some conceptual issue that does not allow such design? 

Best

**Comment by DengPingFan** [comment]
hi,

Yes. I think it can be extended. However, we have no time to do this thing.

Best,


Brenno A. C. Caldato ***@***.***>于2021年3月15日 周一下午9:13写道：

**Comment by BrennoCaldato** [comment]
ok great. Do you have any tips or advice on how to implement these modifications? Such as if it would be better to have one attention mask for each class?

Thanks!

**Comment by DengPingFan** [comment]
I think maybe you can split each class and then use reverse attention.
Finally, multiple class can be merged. Note that each class should be
trained with split loss!



Brenno A. C. Caldato ***@***.***>于2021年3月15日 周一下午9:23写道：

**Comment by BrennoCaldato** [comment]
Thank you for the quick reply. I will try and let you know If I have progress on this

**Comment by DengPingFan** [comment]
Sounds good, thanks!

Brenno A. C. Caldato ***@***.***>于2021年3月15日 周一下午9:36写道：
