### ISSUE TITLE
TypeError:test() missing 2 required positional arguments: 'model' and 'path'

### ISSUE THREAD

**Issue by opencvpython0805** [DengPingFan/PraNet#23]
when I start to train my datasets,there is something wrong:
TypeError:test() missing 2 required positional arguments: 'model' and 'path'

**Comment by GewelsJI** [comment]
Hi, @opencvpython0805,

Could you point out the specific line in the code, please?

Best regards,
Ge-Peng.

**Comment by opencvpython0805** [comment]
Thank you for your prompt reply. The code is correct, I have solved the above problem. Thanks.
