### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by evil-lov** [DengPingFan/PraNet#24]
Traceback (most recent call last):
  File "/home/PraNet-master/MyTrain.py", line 116, in <module>
    train(train_loader, model, optimizer, epoch)
  File "/home/PraNet-master/MyTrain.py", line 50, in train
    loss.backward()
  File "/home/.virtualenvs/pytor1.1/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/.virtualenvs/pytor1.1/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Process finished with exit code 1

**Comment by evil-lov** [comment]
> Traceback (most recent call last):
> File "/home/PraNet-master/MyTrain.py", line 116, in
> train(train_loader, model, optimizer, epoch)
> File "/home/PraNet-master/MyTrain.py", line 50, in train
> loss.backward()
> File "/home/.virtualenvs/pytor1.1/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
> torch.autograd.backward(self, gradient, retain_graph, create_graph)
> File "/home/.virtualenvs/pytor1.1/lib/python3.6/site-packages/torch/autograd/**init**.py", line 93, in backward
> allow_unreachable=True) # allow_unreachable flag
> RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
> 
> Process finished with exit code 1

cuda10.0+cudnn7.6.5+pytorch1.1

**Comment by zihuanqiu** [comment]
reboot your computer may help?

**Comment by evil-lov** [comment]
> 重新启动计算机可能会有所帮助？

**Comment by evil-lov** [comment]
> reboot your computer may help?

**Comment by evil-lov** [comment]
> reboot your computer may help?
No, I finally chose to turn cudnn off, but it will be much slower

**Comment by GewelsJI** [comment]
I suggest you can install it via `conda` toolbox, which can introduce the correct dependencies of GPU automatically.
