### ISSUE TITLE
处理数据

### ISSUE THREAD

**Issue by zhang326905612** [DengPingFan/PraNet#25]
怎么将息肉标签转为mask那

**Comment by DengPingFan** [comment]
hi, 我不太明白你的问题。如果是息肉数据集提供的是bounding box就没有mask，如果已经提供了，那就有mask了。

**Comment by zhang326905612** [comment]
您好，用的是这个数据集吗 一共1000张，然后随机分成训练集和测试集吗，这个是有mask的 我昨天看那个息肉数据他的标注文件是feature后缀的文件，看不懂，所以我问了一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DengPingFan/PraNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月10日(星期一) 晚上10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DengPingFan/PraNet] 处理数据 (#25)





 
hi, 我不太明白你的问题。如果是息肉数据集提供的是bounding box就没有mask，如果已经提供了，那就有mask了。
