### ISSUE TITLE
How can I use PraNet in mutilabel segmentation

### ISSUE THREAD

**Issue by gitouni** [DengPingFan/PraNet#26]
Dear author:
      I have checked your code but it doesn't has a "n_class" paramenter to set the number of classes in segmentation. How can I use this code in mutilabel segmentation with a one-hot output without transforming it into a muti-two-label classification?
Best wishes!

**Comment by DengPingFan** [comment]
Hi, 
You should re-organize the code according to your task.  The current version cannot support your requirement. 

Best,
