### ISSUE TITLE
您好，这篇论文的英文版可以发给我一份吗

### ISSUE THREAD

**Issue by joe660** [DengPingFan/PraNet#28]
您好，这篇论文的英文版可以发给我一份吗？我没法下载英文版本的，邮箱2517449340@qq.com    谢谢啦

**Comment by DengPingFan** [comment]
hi，

我的主页上都能找到：http://dpfan.net/publications/
英文版本：https://arxiv.org/pdf/2006.11392.pdf

祝好，

joe660 ***@***.***> 于2021年6月22日周二 上午7:03写道：
