### ISSUE TITLE
cvc-colonDB数据集图片问题

### ISSUE THREAD

**Issue by whatcolor1** [DengPingFan/PraNet#30]
非常感谢您的这份工作.我下载了您提供的数据集后,发现测试集/data/TestDataset/CVC-ColonDB/images/380.png图片似乎有点问题,我想问一下是原始图片就是这样的还是上传的过程中出了错?

**Comment by evil-lov** [comment]
> 非常感谢您的这份工作.我下载了您提供的数据集后,发现测试集/data/TestDataset/CVC-ColonDB/images/380.png图片似乎有点问题,我想问一下是原始图片就是这样的还是上传的过程中出了错?

或许是您下载的时候出现了问题，我复现的时候没有出现这个问题，重新下载一下数据集或许有效。

**Comment by DengPingFan** [comment]
> 非常感谢您的这份工作.我下载了您提供的数据集后,发现测试集/data/TestDataset/CVC-ColonDB/images/380.png图片似乎有点问题,我想问一下是原始图片就是这样的还是上传的过程中出了错?

hi, 我们下载原始数据是这样的，你可以再去原来的数据集上检查一下。另外一张结果图应该不会对最后的平均性能带来太大的变化
