### ISSUE TITLE
Where can I download the dataset？

### ISSUE THREAD

**Issue by qyl-123** [DengPingFan/PraNet#33]
Thanks  for your wonderful job.could you tell me where can download CVC-ColonDB datasets.please.I can not find

**Comment by DengPingFan** [comment]
Please refer to the following link: http://vi.cvc.uab.es/colon-qa/cvccolondb/

**Comment by caijinyue** [comment]
> Please refer to the following link: http://vi.cvc.uab.es/colon-qa/cvccolondb/

This link can not be opened now.

**Comment by chqwer2** [comment]
Can anyone register with this dataset and download it? 

> > Please refer to the following link: http://vi.cvc.uab.es/colon-qa/cvccolondb/
> 
> This link can not be opened now.

Can anyone register with this dataset and download it?
