### ISSUE TITLE
请问数据集在哪里下载呀

### ISSUE THREAD

**Issue by qyl-123** [DengPingFan/PraNet#34]
CVC-ColonDB这个数据集一直找不到，哭了

**Comment by DengPingFan** [comment]
Hi，
请参考如下网址进行申请：http://vi.cvc.uab.es/colon-qa/cvccolondb/
对应论文：https://linkinghub.elsevier.com/retrieve/pii/S0031320312001185

**Comment by Liqq1** [comment]
您好！上述http://vi.cvc.uab.es/colon-qa/cvccolondb/这个网站好像打不开了
我在其他文章介绍中看到CVC-ColonDB是300张图片，请问我该如何确认CVC-ColonDB中是300张还是380张图像？
<img width="614" alt="image" src="https://user-images.githubusercontent.com/54054113/154259899-60bc9c4b-01a7-497b-ba7f-34e8b04148e8.png">

**Comment by DengPingFan** [comment]
hi，

你可以根据发表论文的时间来判断一下，可能作者后来更新了。我们也提供了PraNet的训练和测试数据，可以自行下载。

祝好，

**Comment by Liqq1** [comment]
> hi，
> 
> 你可以根据发表论文的时间来判断一下，可能作者后来更新了。我们也提供了PraNet的训练和测试数据，可以自行下载。
> 
> 祝好，

好的，明白了。应该是后续的更新问题。谢谢！

**Comment by GewelsJI** [comment]
问题已解决！
