### ISSUE TITLE
Information about RFB_modified function

### ISSUE THREAD

**Issue by NoviceMAn-prog** [DengPingFan/PraNet#35]
Hello, can you give more detailed information about the RFB modified used in the pranet to reduce the number of channels for each scale? What is the source of this module?

**Comment by GewelsJI** [comment]
This module is borrowed from https://github.com/wuzhe71/CPD/blob/e7373b45d9dd213ea5c9ae71f9de9f03b3cbe6c9/model/CPD_ResNet_models.py#L24

You can also refer to RFB paper (Receptive Field Block Net for Accurate and Fast Object Detection. ECCV, 2018).

Thank you for your attention to our paper.

BR,
Ge-Peng.
