### ISSUE TITLE
关于消融实验

### ISSUE THREAD

**Issue by qyl-123** [DengPingFan/PraNet#36]
您好，感谢您优秀的工作, 请问一下消融实验的backbone那一行的评价指标，这里的backbone是直接通过res2net编码，然后直接解码预测得到的嘛，方便的话可以提供一下您backbone的代码吗，谢谢。

**Comment by GewelsJI** [comment]
是的，直接通过res2net进行编码。Backbone (No.1)是一个简单的UNet形状结构但仅仅用到了高三层特征用于训练和预测（不是五层）

代码参考：https://github.com/milesial/Pytorch-UNet/blob/master/unet/unet_model.py
