### ISSUE TITLE
请问：我想应用在多类别分割上，RA模块的channel相乘该如何改呢？

### ISSUE THREAD

**Issue by evilvlso** [DengPingFan/PraNet#37]
首先感谢您的分享！
我想把该网络应用到多类别的分割上（比如为6个类别），但是在每个RA模块中都存在这块代码
```
     #RA
      crop_4 = F.interpolate(ra5_feat, scale_factor=0.25, mode='bilinear')
      x = -1*(torch.sigmoid(crop_4)) + 1
      x = x.expand(-1, 2048, -1, -1).mul(x4)
```
我想请问如果aggregation后的channel为6，那么x channel也为6，那么这块该如何使用x.expand达到和高级特征层一样的channel然后进行相乘操作呢？
如能解答疑问不剩感激！
如有未描述清楚的请联系我： bwdtango@foxmail.com
谢谢

**Comment by GewelsJI** [comment]
您好，

感谢您对我们工作的关注。

我建议对每个类别进行分离的建模，但是要把后续的特征根据不同类别进行分离做，我初步猜测这样子会引入较大的计算量，您可以具体实现试试

祝好，
季葛鹏
