### ISSUE TITLE
matlab 代码提示“数组索引必须为正整数或逻辑值。”问题

### ISSUE THREAD

**Issue by 15104356116** [DengPingFan/PraNet#40]
你好，我想请问一下。我在运行自己的数据集后在matlab中查看结果的数据指标，运行main.m文件时会报错original_WFb中第33行Et(~GT)=Et(IDXT(~GT))，“数组索引必须为正整数或逻辑值。”这个问题该怎么办呢？我之前跑原数据集的时候并没有出现这个问题。当我将代码改为
Et(GT)=Et(IDXT(GT)); %To deal correctly with the edges of the foreground region
EA = imfilter(~Et,K);
得到的dice和iou相关值都为0.

**Comment by DengPingFan** [comment]
你查看一下，是哪张图片报错，原因应该是这个图片的GT是全黑的，因此无法计算IDXT之类的。

**Comment by HanbingCheng0102** [comment]
好的！谢谢！
