### ISSUE TITLE
About data split (train/validation)

### ISSUE THREAD

**Issue by wooseok-shin** [DengPingFan/PraNet#41]
Hi,
I have a question about the experimental setup.

------------------------------------------------------------------------------------------------------------------------------------------
In PraNet paper,
"the images from Kvasir, and CVC-ClinicDB are randomly split into 80% for training, 10% for validation, and 10% for testing."
------------------------------------------------------------------------------------------------------------------------------------------

Contrary to what is mentioned in PraNet paper, there seems to be no validation in the implemented code.
Did you actually train without validation? Or am I missing something?

Thank you.

**Comment by DengPingFan** [comment]
Yes, we train this model without validation. And we use the early-stop strategy. 

Best,

**Comment by wooseok-shin** [comment]
Thanks for your reply.

I have one more question,

Checking the number of TrainDataset.zip files you provide, it seems that the Kvasir and CVC-ClinicDB datasets are used for training together, is that correct?

**Comment by DengPingFan** [comment]
Yes.

**Comment by wooseok-shin** [comment]
Thanks for your reply.
