### ISSUE TITLE
中文版的论文

### ISSUE THREAD

**Issue by coisino** [DengPingFan/PraNet#42]
您好，可以发一下中文版的论文吗，http://dpfan.net/wp-content/uploads/MICCAI20_PraNet_Chinese.pdf，这个网址一直加载不进去。

**Comment by DengPingFan** [comment]
您好，可以到新主页：https://dengpingfan.github.io/
连接：https://dengpingfan.github.io/papers/[2020][MICCAI]PraNet_Chinese.pdf
