### ISSUE TITLE
Could you please provide the code of the comparison model resunet++ and other comparison models

### ISSUE THREAD

**Issue by WangZhi-wz** [DengPingFan/PraNet#47]
Could you please provide the code of the comparison model resunet++ and other comparison models，Thank you very much！

**Comment by GewelsJI** [comment]
Hi, @MOONWZ 

Thank you for your attention to our work first. Please refer to this page: https://github.com/DebeshJha/ResUNetPlusPlus-with-CRF-and-TTA.

Best.
