### ISSUE TITLE
Questions about the citation of the model structure diagram

### ISSUE THREAD

**Issue by Liqq1** [DengPingFan/PraNet#48]
Hi, could I cite the structure diagram in your paper in the relevant technical background section of my undergraduate thesis?
I have already made a citation to the article.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/54054113/172622911-244fea0c-2b2e-4a1a-a6a2-c7521b2517a7.png">

**Comment by DengPingFan** [comment]
Hi, 
Yes. 

Best
