### ISSUE TITLE
About assessment tools

### ISSUE THREAD

**Issue by jue12345** [DengPingFan/PraNet#50]
About assessment tools
Thank you very much for your excellent work.
Downloaded your Matlab evaluation tool: "EvaluationTool_New", run the main.m file directly, all the results show NaN, for example: (Dataset:CVC-300; Model:PraNet) meanDic:NaN;meanIoU:NaN;wFm:NaN ;Sm:NaN;meanEm:NaN;MAE:NaN;maxEm:NaN;maxDice:NaN;maxIoU:NaN;meanSen:NaN;maxSen:NaN;meanSpe:NaN;maxSpe:NaN.

Do you have any ideas on this issue?
Thanks for viewing this question.

**Comment by GewelsJI** [comment]
I guess you may point to the wrong directory for prediction and/or ground truth.

**Comment by jue12345** [comment]
It is indeed the reason you said, the newly generated map is in the "map_new" folder, but the code is "map". Just modify the code.
Thanks for your answer!
