### ISSUE TITLE
Res2Net weights

### ISSUE THREAD

**Issue by mahdiyehbakhshi822** [DengPingFan/PraNet#53]
Hello
Thanks for the great project
Where should Res2Net weights be placed after downloading?

**Comment by GewelsJI** [comment]
@mahdiyehbakhshi822 Hi, res2net weight file will be automatically downloaded by this [line](https://github.com/DengPingFan/PraNet/blob/ba45d69dccbf73d131ecad5f429fec82ff56d790/jittor/lib/Res2Net_v1b.py#L8)
