### ISSUE TITLE
question about mask of Kvasir dataset

### ISSUE THREAD

**Issue by Qinger27** [DengPingFan/PraNet#54]
Thanks for your great work first! It is a great research!
When I check the Kvasir data, I find each mask has more than two different pixel values. I randomly choose a mask and print different pixel values, and it is a list of [0 1 2 3  4 5 6 7 248 249 250 251 253 254 255].  And then I visualize the different pixels values. The 0 represents bachground and 255 represents polyps. The left is around the polyps, i.e. in the  boundary of polyps.
Could you tell me how you process this situation?
Can I change these mask into binary image by sample threshholding?
Really look forward to your reply!
Thanks again!

**Comment by GewelsJI** [comment]
hi @Qinger27 
you need to binarise them using `Image.open(your_file_name).convert('1')`

Thanks
