### ISSUE TITLE
请问网络输出的概率图是如何转换为黑白图像的？

### ISSUE THREAD

**Issue by LiYAnErr** [DengPingFan/PraNet#56]
在MyTest.py里，如下代码所示，网络输出的概率图为res，res中每个像素的范围在0到1之间，misc.imsave函数会自动对res*255。由此，输出的图像应该是一张灰度图。
<img width="565" alt="截屏2022-11-25 18 17 44" src="https://user-images.githubusercontent.com/56872368/203960799-23ec21ad-22a5-46b0-b8cc-6f24e75167cc.png">

可是在论文中，输出的图像是一张黑白二值图像。
<img width="167" alt="截屏2022-11-25 18 23 40" src="https://user-images.githubusercontent.com/56872368/203962400-b8953539-1d28-4180-8b22-a674afef9a9d.png">

请问MyTest.py里输出的灰度图，是如何转换为论文中的黑白二值图像的呢？谢谢～

**Comment by GewelsJI** [comment]
Hi, @LiYAnErr 

The shown figure is gray but not binary since the sigmoid operation is used to get dense and normalised probabilities. I am not sure what you wanna get from this mask, and you can take a thresholding binarized strategy or use the argmax function.

Best.

**Comment by LiYAnErr** [comment]
thank u～
