### ISSUE TITLE
main.m  NaN

### ISSUE THREAD

**Issue by Pr0mlse** [DengPingFan/PraNet#57]
您好，我用matlab进行评估时，所有指标都是NaN，报错如下，请问可能是出现了什么问题？
(Dataset:CVC-300; Model:PraNet) meanDic:NaN;meanIoU:NaN;wFm:NaN;Sm:NaN;meanEm:NaN;MAE:NaN;maxEm:NaN;maxDice:NaN;maxIoU:NaN;meanSen:NaN;maxSen:NaN;meanSpe:NaN;maxSpe:NaN.

**Comment by GewelsJI** [comment]
Hi @Pr0mlse 

I guess you may feed into the wrong data or prediction path. Please check it out. Or you can take a breakpoint debugging to confirm which parameter has a value overflow. Please feel free to comment here if you still have some problems with that.

Best.

**Comment by Pr0mlse** [comment]
It is indeed the reason you said, Thanks for your answer!

**Comment by GewelsJI** [comment]
This issue has been solved.
