### ISSUE TITLE
How to explain "Reverse Attention" module?

### ISSUE THREAD

**Issue by chuxiang93** [DengPingFan/PraNet#8]
Hi,
     First of all, congratulations on your perfect job. I have a question about "Reverse Attention" module. Intuitively we usually use spatial attention to highlight foreground areas, but  it's opposite in your work. Could you give more theoretical explanation?

Thank you,

**Comment by DengPingFan** [comment]
Actually, the reverse attention module is de-facto for salient object detection in the computer vision community.  Some works can be found in [1,2].

In other words, the RA component can mine complementary regions and details by erasing the existing estimated polyp regions from high-level side-output features, where the existing estimation is up-sampled from the deeper layer. 

If you still have other questions, you can also contact me via Email (dengpfan@gmail.com).

Reference: 
[1] Reverse attention for salient object detection. In: ECCV. pp. 234{250 (2018)
[2] Bilateral attention network for rgb-d salient object detection, arXiv, 2020.
